//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Resources;
using System;

namespace nanoFramework.WebServerAndSerial
{
    
    internal partial class ResourceWeb
    {
        private static ResourceManager manager;
        internal static ResourceManager ResourceManager
        {
            get
            {
                if ((ResourceWeb.manager == null))
                {
                    ResourceWeb.manager = new ResourceManager("nanoFramework.WebServerAndSerial.ResourceWeb", typeof(ResourceWeb).Assembly);
                }
                return ResourceWeb.manager;
            }
        }
        internal static string GetString(ResourceWeb.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(ResourceWeb.BinaryResources id)
        {
            return ((byte[])(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [SerializableAttribute()]
        internal enum BinaryResources : short
        {
            favicon = -22914,
        }
        [SerializableAttribute()]
        internal enum StringResources : short
        {
            style = -5605,
        }
    }
}
